version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "major"
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]
